modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "mineplanetplus"
version = "${version}"
displayName = "MineplanetPlus"
authors = ""${modAuthor}""
description = '''
마인플래닛 서버를 더욱 편리하게 플레이 해보세요!
'''
credits="◆던전헬퍼◆:${dungeonhelperCredits}\n◆스킬타이머◆:${skilltimerCredits}\n◆피시헬퍼◆:${fishhelperCredits}"
#logoFile = ""

[[dependencies.mineplanetplus]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mineplanetplus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
