modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "Unlicense"

[[mods]]
modId = "mineplanetplus"
version = "${version}"
displayName = "MineplanetPlus"
authors = "${modAuthor}"
description = '''
마인플래닛 서버를 더욱 편리하게 플레이 해보세요!
'''
credits='''

◆던전헬퍼◆:${dungeonhelperCredits}
◆스킬타이머◆:${skilltimerCredits}
◆피시헬퍼◆:${fishhelperCredits}"
'''
logoFile = "icon.png"

[[dependencies.mineplanetplus]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mineplanetplus]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "mineplanetplus.mixins.json"

[[mixins]]
config = "mineplanetplus-common.mixins.json"